language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install ."
  - "pip install -r test_requirements.txt"
script:
  - "pytest -v -s --doctest-modules --cov httpie_asap_auth --cov-report term-missing httpie_asap_auth.py tests/"
  - "flake8 httpie_asap_auth.py"
after_success:
  - "coveralls"
